
import { GoogleGenAI } from "@google/genai";

export default async function handler(req: any, res: any) {
  // Ensure we only accept POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  // Securely access the API key from the environment variable
  const apiKey = process.env.GOOGLE_API_KEY;

  if (!apiKey) {
    console.error("Server Error: GOOGLE_API_KEY is missing.");
    return res.status(500).json({ error: 'Server configuration error: API Key missing.' });
  }

  try {
    const { type, prompt, image } = req.body;

    if (!prompt) {
        return res.status(400).json({ error: 'Prompt is required.' });
    }

    const ai = new GoogleGenAI({ apiKey });
    const model = 'gemini-2.5-flash-image';

    let contents;

    if (type === 'image-to-image') {
        if (!image || !image.data || !image.mimeType) {
             return res.status(400).json({ error: 'Image data missing for image-to-image mode.' });
        }
        contents = {
            parts: [
                {
                    inlineData: {
                        mimeType: image.mimeType,
                        data: image.data
                    }
                },
                { text: prompt }
            ]
        };
    } else if (type === 'text-to-image') {
        contents = {
            parts: [{ text: prompt }]
        };
    } else {
        return res.status(400).json({ error: 'Invalid operation type.' });
    }

    const response = await ai.models.generateContent({
        model,
        contents
    });

    // Extract image from response
    const parts = response.candidates?.[0]?.content?.parts;
    if (!parts) {
        throw new Error("No content generated by model.");
    }
    
    let base64Image = null;
    let mimeType = null;
    
    for (const part of parts) {
        if (part.inlineData) {
            base64Image = part.inlineData.data;
            mimeType = part.inlineData.mimeType;
            break;
        }
    }
    
    if (base64Image) {
        return res.status(200).json({ 
            success: true, 
            image: `data:${mimeType};base64,${base64Image}` 
        });
    }
    
    // Check for refusal text or other issues
    const textPart = parts.find((p: any) => p.text);
    if (textPart) {
        return res.status(400).json({ error: `Model Refused: ${textPart.text}` });
    }

    throw new Error("No image data found in response.");

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    
    let errorMessage = error.message || "Internal Server Error";
    
    // Provide user-friendly error messages for common issues
    if (errorMessage.includes('429') || errorMessage.includes('quota') || errorMessage.includes('RESOURCE_EXHAUSTED')) {
        errorMessage = "System Busy. High traffic detected. Please try again in a moment.";
    } else if (errorMessage.includes('SAFETY') || errorMessage.includes('blocked')) {
        errorMessage = "Content Blocked. The request was flagged by safety filters.";
    }

    return res.status(500).json({ error: errorMessage });
  }
}
